spring:
  datasource:
    url: jdbc:mysql://localhost:3306/societyfest
    username: ramakant
    password: Ramakant@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
server:
  port: 8090

jwt:
  secret: B97f830aA72e3d6FCE190bDf81C0Ea912F7cEB934D271CeAcB4F1998e5a7C7F6
  expirationMs: 86400000
