spring:
  datasource:
    url: jdbc:mysql://localhost:3306/societyfest
    username: ramakant
    password: Ramakant@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
server:
  port: 8090

#jwt:
#  secret-file: /Users/ramakant/Documents/ramakant/project_env_files/secret_local.txt
#  expirationMs: 86400000

jwt:
  secret: local_dev_secret
  expirationMs: 86400000





#192.168.0.103